apiVersion: v1
kind: ConfigMap
metadata:
  name: ecomm-app-config
  namespace: test-ns
data:
  ENV_API_URL: "http://localhost:8080/health"
# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: ecomm-app-config
#   namespace: test-ns
# type: Opaque
# data:
#   username: test
#   password: YWRtaW4xMjM=
